backend:
  name: git-gateway
  branch: main
media_folder: "assets/uploads"
public_folder: "/assets/uploads"
site_url: /
display_url: /
locale: zh_Hans
collections:
  - name: "content"
    label: "精选发现"
    files:
      - label: "精选内容列表"
        name: "items"
        file: "content/items.json"
        fields:
          - label: "内容列表"
            name: "items"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - { label: "编号", name: "id", widget: "number", value_type: "int" }
              - { label: "分类", name: "category", widget: "select", options: ["效率", "设计", "数码", "上网"] }
              - { label: "标签名称", name: "tag", widget: "string" }
              - { label: "标题", name: "title", widget: "string" }
              - { label: "摘要", name: "summary", widget: "text" }
